@baseUrl = http://127.0.0.1:8000
@authToken = eyJhbGciOiJSUzI1NiIsImtpZCI6IjM3MzAwNzY5YTA3ZTA1MTE2ZjdlNTEzOGZhOTA5MzY4NWVlYmMyNDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdm90YWNpb25lcy02NWIzOSIsImF1ZCI6InZvdGFjaW9uZXMtNjViMzkiLCJhdXRoX3RpbWUiOjE3NzUwMDQzMTEsInVzZXJfaWQiOiJZa0IzTTdNYTVtWDloNTlZNWFiWnpWNm9OSzQyIiwic3ViIjoiWWtCM003TWE1bVg5aDU5WTVhYlp6VjZvTks0MiIsImlhdCI6MTc3NTAwNDMxMSwiZXhwIjoxNzc1MDA3OTExLCJlbWFpbCI6InZvdGFudGUxQGVqZW1wbG8uY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInZvdGFudGUxQGVqZW1wbG8uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.lqUSgTYFzZqrVZOnnC1PZi6sUKMBYQmavZ-X2iMBtg4aCjYQdaWZk4Sqk2JNYRqfMcmu8GxPeJlZdN9-XwJaODWpJbab2-GZ1DNrVBgamo0Do5AYJKP_NNou736opmHGwlUNuU-c7VNtWudb5hvJJVHxd2fc_VJPnYBiNIAz_4HMtySb6IS2pIAmF_R1JHCaNVc_RBgEeiWeTVJISa7F8Lf_-tisEaouLFtlxXJ6krJHMtLNQd1gBFTL81wEgflNRnOIbonuzxoQCNEbLPMV_R7i7ZN9xtPh1F07C532HdAYQ_DmBXEniYCeRGzwvwB9hnPnUR2DkhBV1TJASH2ITQ
### 1. Registrar un nuevo usuario (Votante)
POST {{baseUrl}}/api/auth/registro/
Content-Type: application/json

{
    "email" : "votante2@ejemplo.com",
    "password" : "password123"
}

### 2. Iniciar sesión para obtener el Token
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
    "email" : "votante1@ejemplo.com",
    "password" : "password123"
}

### 3. Emitir un Voto (POST) - ACTUALIZADO CON NOMBRE DE CANDIDATO
POST {{baseUrl}}/api/votos/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "candidato": "big yaju", 
    "candidato_id": "CAND-003",
    "mesa_id": "MESA-05",
    "comentario": "Voto emitido con auditoría en tiempo real"
}

### 4. Consultar mis votos (GET)
GET {{baseUrl}}/api/votos/
Authorization: Bearer {{authToken}}

### 5. Subir foto de perfil (Cloudinary)
POST {{baseUrl}}/api/perfil/foto/
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="foto.jpg"
Content-Type: image/jpeg

< ./votaciones/foto.jpg
--MiBoundary--